### ISSUE TITLE
BUG: Getting Error while typing in search bar

### ISSUE THREAD

**Issue by sumitkr2000** [onecompiler/cheatsheets#110]
Hey I found a bug in the website. When I type anything in the search bar I am getting an error. Below is a screenshot for reference.

![Screenshot (311)](https://user-images.githubusercontent.com/100675296/193448572-4990e26f-98e3-4d9a-86d2-885b251c4806.png)

**Comment by onecompiler-ops** [comment]
Thank you for reporting it, we have fixed it.
