### ISSUE TITLE
Create a README where all the cheatsheets listed

### ISSUE THREAD

**Issue by imanishbarnwal** [onecompiler/cheatsheets#159]
I want to create a README where all cheatsheets were listed and linked respectively we can also deploy it using GitHub Pages which may help people to find on internet easily.

**Comment by onecompiler-ops** [comment]
@imanishbarnwal All the cheat sheets are automatically synched to https://onecompiler.com/cheatsheets/ every 10 minutes

**Comment by imanishbarnwal** [comment]
Yeah just saw I am closing this issue do check this one #160
