### ISSUE TITLE
Numbering inside markdown files 

### ISSUE THREAD

**Issue by realanupreet** [onecompiler/cheatsheets#184]
### _The issue_

So, while browsing and going through many pull request which are contributing to the .md files which contain some form of numbered headings, there's a common issue or let's say incovinence involved which is manually updating the numbers of the headings when something needs to be added at the top or middle of the file.

_This causes:_

  - unnecessary inconvinence
  - makes it a point of error, if someone forgets to update the numberings
  - not so useful entries in the file version control, similar to the picture attached

![image](https://user-images.githubusercontent.com/72339688/193890404-38ef89e0-2973-4c0a-974b-222cd5e9749b.png)

_Possible solution (clean and simple)_

  - going through each and every .md file which contain such a pattern(numbered heading) and changing the numbers from 
```md
1. first
2. second
3. third
```
to 

```md
1. first
1. second
1. third
```
which will give output as(see raw code):

1. first
1. second
1. third

doing so, will automatically number the headings without a need of updating the numbers manually.

**Ps: I would be happy to do this task!🎀**

**Comment by realanupreet** [comment]
please assign if it seems to be of some value to the repository as a whole

**Comment by onecompiler-ops** [comment]
@realanupreet This is a smart hack, but do not want to go down this path as this creates confusion while editing the markdown files, instead want to spend time on fixing the wrong numbers

**Comment by realanupreet** [comment]
Oh great! 
can think of a scenario like that, will go through the files for finding any wrong numbers. If i find anything tho of that sort ☠️  
:D
