### ISSUE TITLE
New Cheat Sheet Request - [CSS]

### ISSUE THREAD

**Issue by Roytony** [onecompiler/cheatsheets#19]
I saw that you don't have a separate chat sheet for CSS i think it will be good idea to create a separate cheat sheet for CSS if you want i can work on that

**Comment by onecompiler-ops** [comment]
Sure @Roytony  we welcome PRs

**Comment by kshitijmishra27** [comment]
can i work on this new cheetsheet if there are no updates @onecompiler-ops

**Comment by onecompiler-ops** [comment]
@kshitijmishra27 We got a PR for css from @Roytony
