### ISSUE TITLE
New Cheat Sheet Request - npm

### ISSUE THREAD

**Issue by Khushi260** [onecompiler/cheatsheets#209]
npm is a package manager for the JavaScript programming language maintained by npm, Inc. npm is the default package manager for the JavaScript runtime environment Node.js.

Please assign me this issue under hacktoberfest 2022.

**Comment by onecompiler-ops** [comment]
Assigned!

**Comment by Fabayu** [comment]
Pls assign me this @Khushi260

**Comment by Fabayu** [comment]
pls assign me this @onecompiler-ops
