### ISSUE TITLE
please add hacktoberfest label in this repository it will be good for Onecompiler as well as contributers

### ISSUE THREAD

**Issue by kshitijmishra27** [onecompiler/cheatsheets#25]

**Comment by kshitijmishra27** [comment]
![Screenshot (288)](https://user-images.githubusercontent.com/82284180/193316899-1a6f9316-c5cb-4f3f-b959-8115f1af46d5.png)

add like this...😊

**Comment by onecompiler-ops** [comment]
@kshitijmishra27 Thank you for the suggestion, added.
