### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by Mohammed-Shoaib01** [onecompiler/cheatsheets#251]
Hey, can I be assigned to contribute the code of conduct for this repository?

Thank you for your time!

**Comment by onecompiler-ops** [comment]
But how do you know the rules?

**Comment by Mohammed-Shoaib01** [comment]
I was going to add the Covenant Code of Conduct and iterate from there.

If it isn't applicable, could you advice on how I could help make one if possible?

Thank you for your time!

**Comment by onecompiler-ops** [comment]
Please contribute to tech cheat sheets instead
