### ISSUE TITLE
Modification in PHP sheet

### ISSUE THREAD

**Issue by Rancho2002** [onecompiler/cheatsheets#253]
I want to modify the php cheatsheet by adding some more super useful super global variables and its uses. Please assign this task to me @onecompiler-ops

**Comment by onecompiler-ops** [comment]
Assigned!

**Comment by Rancho2002** [comment]
pls add hacktoberfest label to my issue @onecompiler-ops 🙏

**Comment by onecompiler-ops** [comment]
We will add to PRs

**Comment by Rancho2002** [comment]
Pls check my PR #294  @onecompiler-ops

**Comment by Rancho2002** [comment]
closed as merged #294
