### ISSUE TITLE
New Cheat Sheet Request - [cpp.md]

### ISSUE THREAD

**Issue by vinayakU94** [onecompiler/cheatsheets#260]
Some information about the naming convention of variables in c++ is missing in cpp.md file that " a variable can not be a keyword "
I would like to add that missing information. please assign that to me.

**Comment by vinayakU94** [comment]
please assign this to me

**Comment by onecompiler-ops** [comment]
Assigned!

**Comment by vinayakU94** [comment]
pull request has been sent. Please review
