### ISSUE TITLE
Want to add README.MD

### ISSUE THREAD

**Issue by Rancho2002** [onecompiler/cheatsheets#310]
In this awesome repository, there is no readme.md where contributors can read and learn how to contribute in this repository, so I want to add one readme.md in this repository. Kindly assign this to me @onecompiler-ops

**Comment by Satakshijain** [comment]
@onecompiler-ops I want to contribute to this project by adding a README.MD to it please assign this issue to me

**Comment by onecompiler-ops** [comment]
We have some unfinished code changes to support README. Please ignore this for now.
