### ISSUE TITLE
please add 2 more labels too that are hacktoberfest-accepted and hacktoberfest2022

### ISSUE THREAD

**Issue by kshitijmishra27** [onecompiler/cheatsheets#36]
![image](https://user-images.githubusercontent.com/82284180/193401832-ad82e90c-cff7-4c7e-82bc-cd08700c5a7a.png)

**Comment by kshitijmishra27** [comment]
@onecompiler-ops  add 2 more labels "hacktoberfest-accepted" and "hacktoberfest2022"

**Comment by onecompiler-ops** [comment]
done!
