### ISSUE TITLE
Imrproving the Git cheatsheet.

### ISSUE THREAD

**Issue by detronetdip** [onecompiler/cheatsheets#42]
We can add rebase command to the git cheatsheet.

**Comment by detronetdip** [comment]
I want to work on this issue. @onecompiler-ops  please assign me this issue.

**Comment by onecompiler-ops** [comment]
@detronetdip done

**Comment by SxxAq** [comment]
I want to work with this issue. @onecompiler-ops please assign me this issue. I can add a few specific diff command in inspect section also in few in another

**Comment by onecompiler-ops** [comment]
@SxxAq  assigned
