### ISSUE TITLE
Adding resources to some cheatSheets

### ISSUE THREAD

**Issue by kshitijmishra27** [onecompiler/cheatsheets#47]
@onecompiler-ops 
i have seen a lot of cheatsheets also contains links to related famous resources like youtube playlists etc where people can learn from those playlists that particular language so can i add resource section and some playlist links to cpp.md and java.md ????

as i know some famous YouTubers having 200K+ subscribers you teach well 😄

**Comment by onecompiler-ops** [comment]
Sorry, @kshitijmishra27  we are strict about the external links, we only allow links to official websites. 
For example, in Java we allow links to java.com or oracle.com only

**Comment by kshitijmishra27** [comment]
ohk no issues 😄
