### ISSUE TITLE
New Cheat Sheet Request - [Solidity]

### ISSUE THREAD

**Issue by arefathi** [onecompiler/cheatsheets#49]
Hello there @onecompiler 

I am quite fascinated with awesome lists and cheatsheets that I find on GitHub as they make my life easier as a developer. This year for Hacktoberfest 2022 - I decided to go the low-code way and wanted to contribute to some repos such as this. I see that you are missing a Solidity cheat sheet. I would like to start that cheatsheet and share it with the general list. Let me know how to proceed.

I am starting out my blockchain journey, but I have extensive resources regarding Solidity that I would be able to share. Assign me the issue so that I can proceed. 

Thanks. Appreciate your work and the opportunity.

**Comment by onecompiler-ops** [comment]
@arefathi You are more than welcome to give a PR

**Comment by arefathi** [comment]
Hello again @onecompiler-ops 
I have submitted a PR for the Solidity cheatsheet as discussed earlier. 

I hope it is to your standard. Ping me if there are any issues.
Thanks.
