### ISSUE TITLE
New Cheat Sheet Request - [COBOL]

### ISSUE THREAD

**Issue by SachXD** [onecompiler/cheatsheets#65]
Hey @onecompiler-ops ! i just found this repo via community classroom discord server and i just looked around and found that there was no cheatsheet for the programming language COBOL.I've been programming since the end of my senior year so i just decided to start with non-code contributions and found this repo.

I would really appreciate if you could assign me this issue so that can i can start contributing to this repo.
Thank you and have a great Hacktoberfest '22!

**Comment by onecompiler-ops** [comment]
Assigned!

**Comment by SachXD** [comment]
@onecompiler-ops also add the **hacktoberfest** 22 label if possible. thanks!

**Comment by onecompiler-ops** [comment]
Added the labels!

**Comment by atinder11** [comment]
I would love to work on this please assign me with this.
