### ISSUE TITLE
Information Addition Request - go.md 

### ISSUE THREAD

**Issue by McCune1224** [onecompiler/cheatsheets#89]
Adding Information about Generics in Golang for the go.md file

Also Happy Hacktoberfest 2022 :)
#88

**Comment by Dhruvsinghjadon** [comment]
@onecompiler-ops please assign me this !!

**Comment by McCune1224** [comment]
I realize that in the go.md file Interfaces has not been explained yet. If you want it might be of interest to make an issue/PR on that as well and pre-append it to the Generics section since It mentions interfaces.

**Comment by kshitijmishra27** [comment]
@Dhruvsinghjadon please create your own issues and don't try to streal someone's else issues 😄

**Comment by Dhruvsinghjadon** [comment]
> @Dhruvsinghjadon please create your own issues and don't try to streal someone's else issues 😄
ooooh
I thought, we have to just solve issues, in spite who ever else raised it!! 😄
@kshitijmishra27

**Comment by Dhruvsinghjadon** [comment]
> @Dhruvsinghjadon please create your own issues and don't try to streal someone's else issues 😄

ooooh
I thought, we have to just solve issues, in spite who ever else raised it!! 😄
@kshitijmishra27

**Comment by onecompiler-ops** [comment]
There is no correlation between Issue and PR, anyone can raise the PR against an Issue.

**Comment by onecompiler-ops** [comment]
closing this issue as changes are made part of https://github.com/onecompiler/cheatsheets/pull/88
